server:
  port: 8081

spring:
  config:
    import: "optional:configserver:http://root:passecret@localhost:8080"
  application:
    name: user
  profiles:
    active: development


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/
  instance:
    preferIpAddress: true
